FROM waggle/plugin-base:1.1.1-ml-cuda10.2-l4t
#FROM ecpe4s/waggle-plugin-base:1.1.1-ml-cuda11.0-amd64
 
RUN apt update -y
RUN apt install -y gcc g++ zlib1g-dev autoconf automake make m4 libpython3.6-dev python3-dev wget
 
RUN wget http://tau.uoregon.edu/tau.tgz && tar -zxvf tau.tgz

WORKDIR /tau-2.31.1

RUN ./configure -bfd=download -python -pythonlib=/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu -pythoninc=/usr/include/python3.6m -unwind=download -c++=g++ -cc=gcc
 
ENV PATH="/tau-2.31.1/arm64_linux/bin:$PATH"
 
RUN make -j4 install
 
#ENV PATH="/app/tau-2.31.1/arm64_linux/bin:$PATH"
 
#ENV PATH="/tau-2.31/x86_64/bin:$PATH"
 
ENV PYTHONPATH=/tau-2.31.1/arm64_linux/lib/bindings-python
 
COPY requirements.txt /app/
 
COPY app.py live_metrics.py runtime_metrics.py thread.py start.sh firstprime.py tau_parser.py /app/
COPY tegrastats /usr/bin/tegrastats
 
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
 
RUN apt-get update && apt-get install -y vim
 
RUN pip install -U jetson-stats && python -m pip install psutil && pip install schedule
 
#RUN pip install -U pywaggle[all]
 
RUN pip install -U pywaggle==0.54.0a1
 
## install PAPI 
## run command on host before this works 
# sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
# sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
# sysctl -w kernel.perf_event_paranoid=1
# cat  /proc/sys/kernel/perf_event_paranoid
 
WORKDIR /
 
RUN git clone https://bitbucket.org/icl/papi.git
 
WORKDIR /papi/src
 
#RUN ./configure && make install && make install-man && make install-tests && make install-all 
 
RUN ./configure
RUN make
RUN make install-all
 
#RUN export TAU_METRICS=TIME,PAPI_L1_DCM,PAPI_RES_STL
 
WORKDIR /app
 
                                                                    