"""
[{'device': {'cpu': [{'identifier': 'ARMv7 Processor rev 1 (v7l)',
                      'usage': 54}],
             'fanSpeeds': [],
             'power': [],
             'ram': {'free': 69324800, 'total': 262553600, 'usage': 73},
             'storage': [],
             'temperatures': [{'name': 'TEMP-1',
                               'type': 'other',
                               'value': 61.0},
                              {'name': 'TEMP-2',
                               'type': 'other',
                               'value': 64.0},
                              {'name': 'PoE-01',
                               'type': 'other',
                               'value': 49.0},
                              {'name': 'PoE-02',
                               'type': 'other',
                               'value': 51.0}],
"""
